default:
  image: osrf/ros:humble-desktop-full
  tags:
    - ci.inria.fr
    - large
    - linux

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  
stages:
  - build-and-test
  - release

build-and-test-job:
  stage: build-and-test
  cache:
    key: pip-cache
    paths:
      - .cache/pip
  script:
    - apt-get update -y
    - apt-get install -y swig curl python3-pip
    - rosdep install --from-paths . -r -y || true
    - pip install --cache-dir=.cache/pip -r namosim/requirements.txt
    - pip install --cache-dir=.cache/pip -r namoros/requirements.txt
    - colcon build
    - source install/setup.bash
    - ./scripts/test_all.sh
  after_script:
    - rm -rf build/ install/ log/
  except:
    - tags

pages:
  stage: build-and-test
  cache:
    key: pip-cache
    paths:
      - .cache/pip
  script:
    - apt-get update -y
    - apt-get install -y swig curl python3-pip
    - rosdep install --from-paths . -r -y || true
    - pip install --cache-dir=.cache/pip -r namosim/requirements.txt
    - pip install --cache-dir=.cache/pip -r namoros/requirements.txt
    - cd docs
    - make html
    - mv build/html ../public
  artifacts:
    paths:
      - public
  only:
    - main
    - dev
  except:
    - tags
